# Generated by Django 5.0.6 on 2024-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
