# Generated by Django 5.0.6 on 2024-07-25 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_responsable_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=250, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.area')),
            ],
        ),
    ]
