# Generated by Django 5.0.6 on 2024-08-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_bloques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConteoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(max_length=10)),
                ('conteo_del_dia', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.area')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.bloques')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.responsable')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.variedades')),
            ],
        ),
    ]
