# Generated by Django 5.0.6 on 2024-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_variedades_conteodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedades',
            name='nombre',
            field=models.CharField(default='No ingresado', max_length=250),
        ),
        migrations.AlterField(
            model_name='variedades',
            name='caracteristicas',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
        migrations.AlterField(
            model_name='variedades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
