# Generated by Django 5.0.6 on 2024-08-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_variedades_nombre_alter_variedades_caracteristicas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConteoDiario',
        ),
    ]
