# Generated by Django 5.0.6 on 2024-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_delete_conteodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedades',
            name='ciclo_fenologico',
            field=models.CharField(default='No ingresado', max_length=250),
        ),
        migrations.AddField(
            model_name='variedades',
            name='dias_ciclo',
            field=models.CharField(default=80, max_length=250),
        ),
    ]
