# Generated by Django 5.0.6 on 2024-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_alter_variedades_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedades',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=250),
        ),
    ]
