# Generated by Django 5.0.6 on 2024-08-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_alter_variedades_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloques',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('M', 'En Mantenimiento'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='bloques',
            name='numero_camas',
            field=models.CharField(default=30, max_length=250),
        ),
    ]
