databases:
  - name: servidorNaranjo
    plan: free
    databaseName: dbnaranjo
    user: leandro

services:
  - type: web
    plan: free
    name: projectionNaranjo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn projectionNaranjo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorNaranjo
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: projectionnaranjo.onrender.com



# set DATABASE_URL=postgresql://david:RkBAp8ZZaE98t5OiwtpfNnJmI0URw2K9@dpg-cqjettqj1k6c739rc1e0-a.oregon-postgres.render.com/dbcineset