# Generated by Django 5.0.6 on 2024-08-04 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campo', '0001_initial'),
        ('Gestion', '0007_delete_conteodiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteodiario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_diarios', to='Gestion.area'),
        ),
        migrations.AlterField(
            model_name='conteodiario',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_diarios', to='Gestion.bloques'),
        ),
        migrations.AlterField(
            model_name='conteodiario',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_diarios', to='Gestion.responsable'),
        ),
        migrations.AlterField(
            model_name='conteodiario',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_diarios', to='Gestion.variedades'),
        ),
    ]
